services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install --legacy-peer-deps && npm run dev -- --host"
    ports:
      - "3000:5173"
    environment:                  # ← 新增 block
      - VITE_BACKEND=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    # 只挂代码，便于热更新；依赖已打进镜像
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    env_file:
      - .env
