services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend-refactored:/app
      - /app/node_modules
    command: sh -c "npm install --legacy-peer-deps && npm run dev -- --host"
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND=http://localhost:8000
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    # 挂载代码和配置文件
    volumes:
      - ./backend/app:/app/app
      - ./backend/config.json:/app/config.json
    ports:
      - "8000:8000"
    env_file:
      - .env
